grafana:
  service:
    type: NodePort
    nodePort: 30300
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      searchNamespace: monitoring
  defaultDashboardsTimezone: browser

prometheus:
  prometheusSpec:
    retention: 7d
    scrapeInterval: 30s

alertmanager:
  enabled: true
